### ISSUE TITLE
Possible to remove the bottom view of columns?

### ISSUE THREAD

**Issue by hamzabinamin** [pavankataria/SwiftDataTables#14]
Is it possible to not show the column names at the bottom as well?

**Comment by pavankataria** [comment]
From what I remember I believe this should be fairly simple to do. Would creating a property `hidesBottomHeaderLabelsL: Bool` do the trick? That seems to be the natural way to go. I'll pull in the changes tonight and see what I can do. Stay tuned.

**Comment by hamzabinamin** [comment]
Thanks. Also is it somehow possible to add an option to export a table into PDF, XLS?

**Comment by pavankataria** [comment]
Hey, I didn't get time to do it yesterday night. But I'm on it. 

You can create your own class that takes in your data and outputs an CSV file if not an XLS file. Should be pretty straight forward. Also don't forget to give me your details of your app so I can add it in the repo list.

**Comment by hamzabinamin** [comment]
Awesome thanks. I'll let you know if I need help in exporting the tables. 

Yes will share the app once I finish it :)

**Comment by pavankataria** [comment]
> Is it possible to not show the column names at the bottom as well?

🎉 🎉 @hamzabinamin This is now available as of version 0.6.11 🎉 🎉 https://github.com/pavankataria/SwiftDataTables/releases/tag/0.6.11

Set the `shouldShowFooter` property to `false` and inject that configuration object into your data table initialiser and you're good to go. Footer columns will not be drawn.

Let me know how it goes. 🎉

**Comment by pavankataria** [comment]
Let me know how it goes for you @hamzabinamin .

**Comment by hamzabinamin** [comment]
It works thanks @pavankataria

**Comment by hamzabinamin** [comment]
Hey @pavankataria Is there a way to change the color of a particular cell to red or any other color? I sort of want to alert the user by changing the color to red to showcase they are behind their task. In the delegate methods I see that you can only change from highlighted to unhighlighted color.

**Comment by pavankataria** [comment]
Hi, because this issue is closed and your question unrelated to this issue, could you please open up another one outlining the feature you'd like so others can see the title for easier later access. Also is this not possible with the current api? Simply select the colour using the highlighted api

**Comment by hamzabinamin** [comment]
@pavankataria I opened the new issue. Please see that.
