### ISSUE TITLE
search bar doesn't disappear

### ISSUE THREAD

**Issue by amirmahdi2545** [pavankataria/SwiftDataTables#15]
i used this configuration to make the searchbar disappear but no difference 
`public struct DataTableConfiguration {
public var defaultOrdering: DataTableColumnOrder? = nil
public var shouldShowSearchSection: Bool = true
public init(){
}
}`

**Comment by pavankataria** [comment]
You need to set the variable to false. So initialise a ‘DataTableConfiguration’ and set the ‘shouldShowSearchSection’ property to ‘false’ and pass this configuration object into the data tables class. Run the demo project which also shows this done as an example of a search being hidden. You can also use the delegate method and return false to achieve the same.

**Comment by pavankataria** [comment]
Did you get that fixed then? If there’s nothing else I’ll close this issue then.

**Comment by pavankataria** [comment]
I'm going to close this now as this functionality is supported and there hasn't been a response. If you need any more help just post on here and I'll open this issue up again.

**Comment by amirmahdi2545** [comment]
thank you for your help and your library is amazing

**Comment by pavankataria** [comment]
Cheers! If you need any further assistance just post on here. 

Also features and ideas are welcomed too.
