### ISSUE TITLE
could you give me a example on Delegate for maximum customisation?

### ISSUE THREAD

**Issue by yang19930204** [pavankataria/SwiftDataTables#16]
I try my best but can't hide the search bar

**Comment by yang19930204** [comment]
1.this is DataTableConfiguration.swift from pod ，which is different from your example
![wx20180722-023054](https://user-images.githubusercontent.com/29906145/43039048-59980ce2-8d57-11e8-9c4d-6e2cf40b06d7.png)


2.this is my code to hide searchbar
![wx20180722-023030](https://user-images.githubusercontent.com/29906145/43039049-5ca23624-8d57-11e8-837c-72695474105a.png)

**Comment by pavankataria** [comment]
Hi, which version of the cocoapods did you install?

**Comment by pavankataria** [comment]
As you can see, the latest version of the database configuration file looks like this: 
https://github.com/pavankataria/SwiftDataTables/blob/0.6.31/SwiftDataTables/Classes/DataTableConfiguration.swift
This is how yours should look like so long as you have the latest release. 

On another note, you may just be missing to set the delegate :) Setting the delegate would call that method. Add a breakpoint to ensure that `return false` is indeed being called. 

Please get back to me as soon as so I can make sure you've been able to hide the search bar.

**Comment by yang19930204** [comment]
I only use   pod 'SwiftDataTables' in my podfile then it display   ' Installing SwiftDataTables (0.5.3)'  but there 0.6.31

**Comment by yang19930204** [comment]
and when I use  pod 'SwiftDataTables','~>0.6.31'
![1532228067593](https://user-images.githubusercontent.com/29906145/43041801-a05dfd58-8d9d-11e8-93eb-577012bd8983.jpg)

**Comment by yang19930204** [comment]
I have already updated to Using SwiftDataTables (0.6.31) and code this but failure
![1](https://user-images.githubusercontent.com/29906145/43042035-6667c2a8-8da4-11e8-9ff2-cf180018b2f1.png)
![2](https://user-images.githubusercontent.com/29906145/43042036-6a1a294a-8da4-11e8-9b64-cc3a809c2a83.jpg)

**Comment by yang19930204** [comment]
Thank u ,Success!
