### ISSUE TITLE
set the width of header 

### ISSUE THREAD

**Issue by yang19930204** [pavankataria/SwiftDataTables#18]
how to set the Width of columns  not scaling depending on content?

**Comment by pavankataria** [comment]
>     @objc optional func dataTable(_ dataTable: SwiftDataTable, widthForColumnAt index: Int) -> CGFloat

This is the method that you need to implement. Once you override one column's width you'll need to specify the widths for all the other columns.

**Comment by pavankataria** [comment]
@yang19930204 Let me know if that helped so I can close the issue.

**Comment by pavankataria** [comment]
I’m marking this as closed and resolved since you haven’t gotten back so I imagine the solution worked for you. Feel free to open again if you have an issue with this post.
