### ISSUE TITLE
Support for 4.2

### ISSUE THREAD

**Issue by altagir** [pavankataria/SwiftDataTables#23]
`Notification.Name.UIApplicationWillChangeStatusBarOrientation
`
must be changed to
`UIApplication.willChangeStatusBarOrientationNotification`

with Swift 4.2

**Comment by pavankataria** [comment]
Hey nice one. will you be able to submit a pull request for this? I'm currently thinking of the best way to maintain multiple versions of Swift so users using swift 3 and upwards could use this. I have also thought about just dropping support for older versions of Swift by going full steam ahead and migrating the library to the latest version of swift and therefor maintaining one branch only. 

I'd love to hear more opinions about this

**Comment by altagir** [comment]
Sure, I will do a fork and submit pull request, very small change
I would suggest to create branches for that purpose (4.2) and identify them clearly in doc
Some people may want to keep old version of swift, but I usually iron issues right away with latest version.
so would suggest branches 3, 4, 4.2 with the main branch being of of these
regards

https://github.com/pavankataria/SwiftDataTables/pull/24

**Comment by pavankataria** [comment]
Hey Altagir, while the library is relatively small and while I only have short bursts of time available during the week, I'm going to keep the branch setup linear. We'll go with one branch for now and cross the bridge of multi branch at a later point. It seems like it'll take more maintenance time to cherry-pick features across the branches and ensure everything works fine.

**Comment by pavankataria** [comment]
🎉 🎉 @altagir
This is now available as of version 0.7.0 🎉 🎉 https://github.com/pavankataria/SwiftDataTables/releases/tag/0.7.0

Thanks for your pull request! There was some issues merging them in but your request has been integrated! 

Let me know how it goes 🎉
