### ISSUE TITLE
bug in positionning table 

### ISSUE THREAD

**Issue by altagir** [pavankataria/SwiftDataTables#26]
This seems to have been introduced with latest commits

![image](https://user-images.githubusercontent.com/1028010/53305179-291dce80-384c-11e9-8af6-486395623693.png)

**Comment by pavankataria** [comment]
How do you reproduce this? I'm not getting this when I open up the search page on any of the screens.  I'll need more information. 
iOS, device, etc.

**Comment by altagir** [comment]
Uhm... my bad, side effect of fixing the headers width
seems to be obliged to delete DerivedData and build to have proper recompiling of Pod
cannot reproduce here
