### ISSUE TITLE
remove Pods from this repository

### ISSUE THREAD

**Issue by altagir** [pavankataria/SwiftDataTables#27]
I think you should remove the Example/Pods folder and Podfile.lock from this repository

- clone this repo
- cd Example     (already a pods/ there with previous version)
- pod update
`Installing SwiftDataTables 0.7.0 (was 0.6.31)
`

-> remove Pods from repo
-> remove Podfile.lock ? -> or at least update it with 0.7.0

cheers

**Comment by pavankataria** [comment]
I realise there's no value in adding the pods when it's just retrieving them from the source folder. It'll also make things lean and avoid an extra step of having to run pod install on the demo project. Plus it was redundant always lagging behind unless I updated after I uploaded the podspec which would cause more noisy commits.

I'll fix this in the next release. Do double check in case I leave anything out.

**Comment by pavankataria** [comment]
🎉 🎉 @altagir
This is now available as of version 0.7.1 🎉 🎉 https://github.com/pavankataria/SwiftDataTables/releases/tag/0.7.1

Let me know what you think 🎉

**Comment by altagir** [comment]
you need to clean current pods used in sample (Pods/ and Podfile as well as references from project) 

```
cd SwiftDataTables/Example
pod deintegrate SwiftDataTables.xcodeproj
rm Podfile
```

**Comment by pavankataria** [comment]
hah. I noticed immediately after
Uploading another in a bit once I get him

**Comment by pavankataria** [comment]
It’s already been deintegrated along with a few other files, I used a plug-in from a cocoa pods creator; turns out doesn’t remove fake care of everything though deleting pod file etc is my responsibility. I’ll just push and change the tag commit reference

**Comment by altagir** [comment]
it wasn't deintegrated, was still present along with workspace in 0.7.1
I had to do above commands after a fresh pull from 0.7.1.
it will clean workspace and Pods
cheers

**Comment by altagir** [comment]
I put all 3 issues we were talking about in last 3 commits of
https://github.com/altagir/SwiftDataTables/commits/master

**Comment by pavankataria** [comment]
You're right, it wasn't deintegrated properly. I thought everything was dereferenced when I ran the deintegrate plugin. Turns out there were a few remaining pieces left as well as the configurations inside the project.

**Comment by pavankataria** [comment]
Please do try again and let me know if you still see the issue. I've tried on my side and it seems everything has been cleared.

**Comment by pavankataria** [comment]
I'll mark this issue as complete. Can reopen if there's any further issues.

**Comment by altagir** [comment]
sorry for late reply, been a bit overbusy :)
just verified, all perfect, thanks mate
regards
