### ISSUE TITLE
Latest version unavailable

### ISSUE THREAD

**Issue by PSA-hamza** [pavankataria/SwiftDataTables#28]
Hello,
I am unable to install the latest version 0.7.3 which is compatible to swift 4.2

The latest I could install is the 0.6.31

**Comment by rmehta33** [comment]
I am also having the same issue.

EDIT: I got it working by updating my pod repo.

**Comment by PSA-hamza** [comment]
Ok, just did a pod repo update and it works, thanks

**Comment by pavankataria** [comment]
Glad you guys figured it out. You need to run pod update.
