### ISSUE TITLE
searchbar 

### ISSUE THREAD

**Issue by PhoenixLeeSin** [pavankataria/SwiftDataTables#35]
I get an bug..
I write this this code
```Swift
    lazy var dataTable:SwiftDataTable = {
        var options = DataTableConfiguration()
        options.shouldContentWidthScaleToFillFrame = false
        options.defaultOrdering = DataTableColumnOrder(index: 1, order: .ascending)
        options.shouldShowFooter = false
        options.shouldShowSearchSection = false
        let t = SwiftDataTable(data: [], headerTitles: headers, options: options)
        t.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        return t
    }()
```
but the searchbar is not hidden ...

**Comment by pavankataria** [comment]
Which version of Swift are you using? Which version of the package you're using?
Could you follow the issue template please so that I know what your setup looks like?

**Comment by pavankataria** [comment]
This is tied to another issue related to configuration options not working when using a specific initialiser. 

Conversation continued on: #34

**Comment by pavankataria** [comment]
Quick update @350541732 : this has been fixed, please download the latest version! 
https://github.com/pavankataria/SwiftDataTables/releases/tag/0.8.0
