### ISSUE TITLE
Is it possible to freeze last row of table?

### ISSUE THREAD

**Issue by anismansuri63** [pavankataria/SwiftDataTables#37]
I've some requirement in which I need to freeze last row of table.
It is possible?

**Comment by pavankataria** [comment]
You're in luck, the freezing columns  feature was recently built. 
This feature is available from version `0.8.0` so update your pods to the latest version 🎉 🎉 

You can check out the release notes and tutorial here:
https://github.com/pavankataria/SwiftDataTables/releases/tag/0.8.0

Does this help?

**Comment by anismansuri63** [comment]
Thank for the help, but it will freeze the column. I wanted to freeze the last row
I made changes in **SwiftDataTable, DataStructureModel** init method. Footer values passed along side header values.
Enabled shouldShowFooter in DataTableConfiguration.
Thanks again.

**Comment by pavankataria** [comment]
What do the shouldShowFooter properties have anything to do with this?
Are you freezing the footer or the row itself? Would be interested to find out what you did in a bit more detail incase this is going to be useful for someone else.
