### ISSUE TITLE
Unexpected duplicate tasks 

### ISSUE THREAD

**Issue by anudeep94** [pavankataria/SwiftDataTables#48]
Hi,
I was releasing an update for our app to iOS 13, from Xcode 11.3  and archiving it fails with errors like:

Unexpected duplicate tasks:
1) Target 'SwiftDataTables' (project 'Pods') has copy command from '/Users/ecosoft/Desktop/BS OE Survey 2/Pods/SwiftDataTables/SwiftDataTables/SwiftDataTables.bundle/column-sort-ascending.png' to '/Users/ecosoft/Library/Developer/Xcode/DerivedData/BS_OE_Survey-fykbjydhfdxtjiaimfbylnuedznk/Build/Intermediates.noindex/ArchiveIntermediates/BS OE Survey/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SwiftDataTables.framework/column-sort-ascending.png'
2) Target 'SwiftDataTables' (project 'Pods') has copy command from '/Users/ecosoft/Desktop/BS OE Survey 2/Pods/SwiftDataTables/SwiftDataTables/SwiftDataTables.bundle/column-sort-ascending.png' to '/Users/ecosoft/Library/Developer/Xcode/DerivedData/BS_OE_Survey-fykbjydhfdxtjiaimfbylnuedznk/Build/Intermediates.noindex/ArchiveIntermediates/BS OE Survey/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SwiftDataTables.framework/column-sort-ascending.png'

**Comment by KarasIlia** [comment]
Hi! 
I have the same problem when trying to archive, does anyone know how to solve it?

UPD: Removing references to 3 files "column-sort-ascending.png", "column-sort-descending.png" and "column-sort-unspecified.png" in Pods/SwiftDataTables helped to me.

**Comment by pavankataria** [comment]
Are you saying this prevents you from uploading completely?

**Comment by pavankataria** [comment]
Did you resolve your issue in the end @anudeep94?

Please update to the latest version of SwiftDataTables. 
That folder is no longer there. 

Thank you @KarasIlia for being so helpful to @anudeep94 while I was away.

**Comment by kishorekumarek** [comment]
@pavankataria I have this issue, should we delete the files manually to solve this?

I am already in the latest version SwiftDataTables (0.8.1), but still get this error.

All these image files getting added in both classes and resources directory. We may have to update the podspec to exclude path to these files in classes directory, if we change it to following it works.

![image](https://user-images.githubusercontent.com/7402115/78663912-07fb2e80-78e4-11ea-849e-17f1e3354ae2.png)

**Comment by dcoletto** [comment]
I have this issue too, right after running pod install with this new pod added. Any news on this?

**Comment by pavankataria** [comment]
Can you folks try the latest master now please and let me know if you still get this issue on your side? This should be resolved now.

**Comment by pavankataria** [comment]
@tringkishorekumar thank you. Will fix this and push to master.

**Comment by vahidnety** [comment]
> @tringkishorekumar thank you. Will fix this and push to master.

I fixed in my local code this way:
go to file>Workspace Settings> set build system to Legacy Build system.
then compile and enjoy your life.

**Comment by dipen-apptrait** [comment]
I solved this issue by deleting this png file from the compile sources under the build phase of this pod.

**Comment by pavankataria** [comment]
@dipen-apptrait @vahidnety @dcoletto @tringkishorekumar @KarasIlia @anudeep94
![image](https://user-images.githubusercontent.com/1791244/101439923-8f82bc80-390d-11eb-98c0-6931198976f8.png)

Please upgrade to the latest version of `SwiftDataTables` (0.8.2) to receive a fix for this issue. Thank you. 

 🚀  SwiftDataTables (0.8.2) successfully published on  📅  December 8th, 04:03
👍 Share with your friends and colleagues!
