### ISSUE TITLE
Delegate method for row color: changes Columns instead of Rows!

### ISSUE THREAD

**Issue by PerplexedFox** [pavankataria/SwiftDataTables#50]
Hi,

I need a way to fixedly highlight one row (depending on data, do that after sorting the right row is still highlighted)
So I implemented the delegate functions 
```
 func dataTable(_ dataTable: SwiftDataTable, highlightedColorForRowIndex at: Int) -> UIColor
```
 and
```
func dataTable(_ dataTable: SwiftDataTable, unhighlightedColorForRowIndex at: Int) -> UIColor}
```

however, instead of alternating rows (horizontally), these methods color the whole columns!

Can you fix it?

**Comment by pavankataria** [comment]
Hi, the API currently does not support resizing a column automatically based on the width of its content as it is out of the original scope. My hope is to be able to figure out the best way to do this.

Until then you'll have to decide what width you'd like for your columns and specify the width by opting out of automatic width calculation and using the `widthForColumnAt` delegate method.

**Comment by PerplexedFox** [comment]
Hi, 
thank you for the answer. The biggest issue I have is that this resizing works seemingly at random so that many headers are cropped, while others made very wide. Do you have any idea why the cropping occurs? 
<img width="653" alt="Screenshot 2020-04-02 at 19 30 34" src="https://user-images.githubusercontent.com/60888823/78279869-7ae95b80-7518-11ea-89e7-2620da42f2ff.png">
<img width="575" alt="Screenshot 2020-04-02 at 19 30 19" src="https://user-images.githubusercontent.com/60888823/78279873-7cb31f00-7518-11ea-9101-be040e143364.png">
<img width="330" alt="Screenshot 2020-04-02 at 19 32 20" src="https://user-images.githubusercontent.com/60888823/78279998-ad935400-7518-11ea-9d7d-51221c7fb74c.png">

**Comment by pavankataria** [comment]
Could you upload a bare-bones project on your github that highlights this issue so that I can test it?
This looks unsightly and needs to be resolved.

**Comment by pavankataria** [comment]
You've already raised this in a new issue which is the correct way to go about this. We can leave this issue open for the colouring issue. 

You mentioned highlighting rows after sorting, could you please explain what you expect in regards to your row colouring?

**Comment by pavankataria** [comment]
![Screenshot 2020-04-05 at 13 06 27](https://user-images.githubusercontent.com/1791244/78485409-d09f4d00-773e-11ea-9a15-5b4f108140b8.png)
Rows are colouring as expected.  If you have a different expectation please outline how you'd like to interface with the library and what coloring feature you would like to see.

**Comment by PerplexedFox** [comment]
Hi, thanks for your answer.

Since I may not share my project, I created a new one with two view Controllers but the same data. You can find it here: https://github.com/PerplexedFox/SwiftDataTables_minEx

You will find the example of the color delegate function problem(`func dataTable(_ dataTable: SwiftDataTable, unhighlightedColorForRowIndex at: Int) -> UIColor` and `func dataTable(_ dataTable: SwiftDataTable, highlightedColorForRowIndex at: Int) -> UIColor`) I described above

for the following code

<img width="836" alt="Screenshot 2020-04-14 at 12 28 52" src="https://user-images.githubusercontent.com/60888823/79215122-822f3400-7e4b-11ea-9214-e80a7d092f1e.png">

this is the result

<img width="337" alt="Screenshot 2020-04-14 at 12 28 45" src="https://user-images.githubusercontent.com/60888823/79215225-95da9a80-7e4b-11ea-835f-1ca0e6bfe607.png">

**Comment by PerplexedFox** [comment]
Got it.

in 
```
public func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
        let cellViewModel = self.rowModel(at: indexPath)
        
        if cellViewModel.highlighted {
            cell.contentView.backgroundColor = delegate?.dataTable?(self, highlightedColorForRowIndex: indexPath.item) ?? self.options.highlightedAlternatingRowColors[indexPath.section % self.options.highlightedAlternatingRowColors.count]
        }
        else {
            cell.contentView.backgroundColor = delegate?.dataTable?(self, unhighlightedColorForRowIndex: indexPath.item) ?? self.options.unhighlightedAlternatingRowColors[indexPath.section % self.options.unhighlightedAlternatingRowColors.count]
        }
```

**indexPath.item** must be replaced by **indexPath.section**
