### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by hemant3370** [pavankataria/SwiftDataTables#58]
Unexpected duplicate tasks:
1) Target 'SwiftDataTables' (project 'Pods') has copy command from '/Users/hemantsingh/Documents/GitHub/ios-sam-mobile/Pods/SwiftDataTables/SwiftDataTables/SwiftDataTables.bundle/column-sort-descending.png' to '/Users/hemantsingh/Library/Developer/Xcode/DerivedData/SAM-chkwwwclzakjpvctkzvdqqdtyich/Build/Products/Dev-iphonesimulator/SwiftDataTables/SwiftDataTables.framework/column-sort-descending.png'
2) Target 'SwiftDataTables' (project 'Pods') has copy command from '/Users/hemantsingh/Documents/GitHub/ios-sam-mobile/Pods/SwiftDataTables/SwiftDataTables/SwiftDataTables.bundle/column-sort-descending.png' to '/Users/hemantsingh/Library/Developer/Xcode/DerivedData/SAM-chkwwwclzakjpvctkzvdqqdtyich/Build/Products/Dev-iphonesimulator/SwiftDataTables/SwiftDataTables.framework/column-sort-descending.png'

**Comment by pavankataria** [comment]
What are the exact steps you run to get this error? Are you able to product this error with the example app?

Please state what you did to get this.

**Comment by hemant3370** [comment]
I just followed the cocoapod integration and the project gives out this error on building.

**Comment by ArtemRiabtsev** [comment]
Go to xCode -> Product -> Archive: and got this issue.

**Comment by PerplexedFox** [comment]
same here

**Comment by kaomte** [comment]
Same here. Just got this after trying to upgrade to XCode 12.

**Comment by kaomte** [comment]
I fixed this in this pull request #60

**Comment by pavankataria** [comment]
Thanks @kaomte .
