### ISSUE TITLE
Automatic width calculation issue

### ISSUE THREAD

**Issue by vahidnety** [pavankataria/SwiftDataTables#59]
Please take a look at the screen shot below.
When i scroll to right side, it looks that the width of the cell calculated double thats why it goes to empty until reach to the end of the cell.
How to fix it? Can i fix it in my side? or i have to wait for new version of the library? Thanks your help on this.

![2020-07-21 11 03 55](https://user-images.githubusercontent.com/2021111/88008452-e1839b00-cb42-11ea-91c4-dc3215e3a82d.jpg)

**Comment by pavankataria** [comment]
That's interesting, I would say provide a demo project but I'm currently working on a prototype that will fundamentally change the way cell widths are calculated. So fixing this now might be redundant. Bare with me on this.

**Comment by vahidnety** [comment]
> That's interesting, I would say provide a demo project but I'm currently working on a prototype that will fundamentally change the way cell widths are calculated. So fixing this now might be redundant. Bare with me on this.

Thanks so i consider it close for now and if it happen with the future library, then will reopen it.

**Comment by ndreisg** [comment]
I have the same issue. @pavankataria: Any news about that fundamental changes?

**Comment by pavankataria** [comment]
Related:
https://github.com/pavankataria/SwiftDataTables/issues/74

https://github.com/pavankataria/SwiftDataTables/issues/74#issuecomment-3769630935
